# Generated by Django 4.2.7 on 2023-12-19 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=10, verbose_name="이름")),
                (
                    "user_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format '+123456789'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="전화번호",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, verbose_name="아이디")),
                ("user_pw", models.CharField(max_length=30, verbose_name="비밀번호")),
                ("user_dep", models.CharField(max_length=10, verbose_name="부서")),
                ("user_email", models.EmailField(max_length=254, verbose_name="이메일")),
            ],
        ),
    ]
