# Generated by Django 4.2.7 on 2023-12-21 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="documents/")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=10, verbose_name="이름")),
                (
                    "user_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="010-****-****의 형태로 입력해주세요.",
                                regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$",
                            )
                        ],
                        verbose_name="전화번호 (010-****-**** 의 형태로 입력해주세요.)",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, verbose_name="아이디")),
                ("user_pw", models.CharField(max_length=30, verbose_name="비밀번호")),
                ("user_dep", models.CharField(max_length=10, verbose_name="부서")),
                ("user_email", models.EmailField(max_length=254, verbose_name="이메일")),
            ],
        ),
    ]
