# Generated by Django 4.2 on 2023-12-21 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fillow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(blank=True, upload_to="fillow")),
                ("answer", models.CharField(blank=True, max_length=300)),
                ("title", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(blank=True, max_length=10)),
                ("edit_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qna",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
