# Generated by Django 4.2 on 2023-12-20 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fillow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="documents/")),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="010-****-****의 형태로 입력해주세요.",
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$",
                    )
                ],
                verbose_name="전화번호 (010-****-**** 의 형태로 입력해주세요.)",
            ),
        ),
    ]
