# Generated by Django 4.2.7 on 2023-12-21 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fillow", "0002_customizeuser_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomizeUser",
            new_name="AdditionalInform",
        ),
    ]
