# Generated by Django 4.2 on 2023-12-22 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fillow", "0002_qna"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qna",
            name="image",
        ),
    ]
