# Generated by Django 4.2 on 2023-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fillow", "0003_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email_cc",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="email",
            name="email_from",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="email",
            name="email_text_content",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="email",
            name="email_to",
            field=models.CharField(max_length=1000),
        ),
    ]
